#!/bin/bash

# disable path name expansion or * will be expanded in the line
# cmd=( $line )
set -f

monitor=${1:-0}
geometry=( $(herbstclient monitor_rect "$monitor") )
if [ -z "$geometry" ] ;then
    echo "Invalid monitor $monitor"
    exit 1
fi

# geometry has the format: WxH+X+Y
x=${geometry[0]}
y=${geometry[1]}
panel_width=${geometry[2]}
panel_height=20
font='Monospace-10.5'
conky_tag_font='Monospace-9'
title_font='Wenquanyi Zen Hei Sharp-10'
bgcolor=$(herbstclient get frame_border_normal_color)
selected_bg=$(herbstclient get window_border_active_color)
selected_fg='#101010'
separator_fg=$selected_bg
separator="^fg($separator_fg)|^fg()"

# Maximum allowed length of tabbar (in chars) and width of rightside part(in
# pixel).
# I have to hardcode them before I found a way to calculate pixel width of
# chars in xft fonts (textwidth only supports X fonts).
tabbar_width=104
right_width=184

mydir=$(dirname "$0")
conkyrc=$mydir/conkyrc
conkyfmt=$mydir/conkyfmt
panelfmt=$mydir/panelfmt

childpid=()

herbstclient pad $monitor $panel_height

trayer --edge top --align right\
    --widthtype request --height $panel_height \
    --margin $(( right_width + 6 )) --padding 5 &
childpid+=($!)

{
    while true; do
        date +'date	^fg(#efefef)%H:%M:^fg(#909090)%S, %m-^fg(#efefef)%d %a'
        sleep 1 || break
    done &
    childpid+=($!)

    if [ -z $DISABLE_CONKY ]; then
        conky -c $conkyrc > >(HEIGHT=$panel_height TAG_FONT=$conky_tag_font $conkyfmt) &
        childpid+=($!)
    fi

    herbstclient --idle
    kill "${childpid[@]}"
} | {(
    export monitor separator selected_fg selected_bg title_font
    export panel_height panel_width right_width tabbar_width
    "$panelfmt"
)} |
    dzen2 -w $panel_width -x $x -y $y \
          -fn "$font" -h $panel_height \
          -ta l -bg "$bgcolor" -fg '#efefef'
